### ISSUE TITLE
Bug à l'édition du projet

### ISSUE THREAD

**Issue by veroniquemonaco** [WildCodeSchool/orleans-0217-wildbook#93]
A l'edition/modification du projet les wilders associés au projet et le projet sont supprimés de la table wilder et project

**Comment by veroniquemonaco** [comment]
Sylvain,
je n'arrive pas à reproduire la suppression du projet et des wilders, par contre je ne peux pas supprimer un wilder associé à un projet en mode edit

**Comment by sblondeau** [comment]
j'ai modifié les cascade, le remove ne devait être que dans les entités projet et wilder sur la relation avec projectWilder et non dans l'autre sens. 
En effet, si tu supprimes un projet, tu supprime les liens projetWilder associés, non les wilders.
Par contre si tu supprime un lien projetWilder, tu ne supprimes pas wilder et projet associés !
